### PR TITLE
ramda@0.22.x

### LINKED ISSUE #243: ramda 0.22.1?

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #243

ramda/ramda#1850

/cc @johannestroeger

### CODE REVIEW

**Comment by scott-christopher** [comment]
:mushroom:

**Comment by johannestroeger** [comment]
@davidchambers this hasn't been released or?

**Comment by davidchambers** [comment]
@johannestroeger, are you asking whether we've released a new version of Sanctuary since merging this pull request? If so, the answer is no.

**Comment by johannestroeger** [comment]
is there a reason? should be patch or?

**Comment by davidchambers** [comment]
The next release needs to be v0.12.0, but I'd like to merge some other pull requests before then. Hopefully in a couple of weeks you'll be down to one version of Ramda again. :)

**Comment by johannestroeger** [comment]
ok, thanks for your effort!

**Pull request merged**
